// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeApp() (App, error) {
	context := getRootContext()
	clientset, err := getKubeClient()
	if err != nil {
		return nil, err
	}
	mainApp := newApp(context, clientset)
	return mainApp, nil
}
