apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-unseal.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-unseal.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "unseal_keys": {{ .Values.unsealKeys | toJson }}
    }
